import numpy as np
from dynamic_constants import ANGULAR_MOMENTUM, ENGINE_ORIENTATION


def propulsion(thrust_input, mach, altitude):
    """
    Calculates the force and moment generated by the engines.

    :param thrust_input: amount of % thrust input. ranges between 0-1.
    :param mach: current mach speed.
    :param altitude: current altitude.
    :return: the force and moment generated by the engines as a numpy array.
    """


    if thrust_input <= 0:
        thrust = thrust_idle
    elif 0 < thrust_input <= 0.77:
        thrust = thrust_idle + (thrust_mil - thrust_idle) * thrust_input / 0.77
    else:
        thrust = thrust_mil + (thrust_max - thrust_mil) * (thrust_input - 0.77) / 0.77


    return np.array([Fp, Mp])